package investment;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-01-27T21:28:55.768-05:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "MoveInvestmentService", 
                  wsdlLocation = "http://uml.cs.uga.edu:8080/sahar_voghoei_move/MoveInvestment?wsdl",
                  targetNamespace = "http://investment/") 
public class MoveInvestmentService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://investment/", "MoveInvestmentService");
    public final static QName MoveInvestmentPort = new QName("http://investment/", "MoveInvestmentPort");
    static {
        URL url = null;
        try {
            url = new URL("http://uml.cs.uga.edu:8080/sahar_voghoei_move/MoveInvestment?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MoveInvestmentService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://uml.cs.uga.edu:8080/sahar_voghoei_move/MoveInvestment?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MoveInvestmentService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MoveInvestmentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MoveInvestmentService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MoveInvestmentService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MoveInvestmentService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MoveInvestmentService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MoveInvestment
     */
    @WebEndpoint(name = "MoveInvestmentPort")
    public MoveInvestment getMoveInvestmentPort() {
        return super.getPort(MoveInvestmentPort, MoveInvestment.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MoveInvestment
     */
    @WebEndpoint(name = "MoveInvestmentPort")
    public MoveInvestment getMoveInvestmentPort(WebServiceFeature... features) {
        return super.getPort(MoveInvestmentPort, MoveInvestment.class, features);
    }

}
